### ISSUE TITLE
После обновления до НА Core 2024.1.0 появились предупреждения.

### ISSUE THREAD

**Issue by seny110188** [AlexxIT/GyverLamp#12]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1194
Integration: Освещение (documentation, issues)
First occurred: 11:18:48 (3 occurrences)
Last logged: 11:18:49

Entity None (<class 'custom_components.gyverlamp.light.GyverLamp'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|17: 21> and color modes, please report it to the author of the 'gyverlamp' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by AlexxIT** [comment]
Проверьте мастер версию

**Comment by seny110188** [comment]
Проверил в мастер версии предупреждения нет.

**Comment by AlexxIT** [comment]
А лампа то полноценно работает? :)

**Comment by seny110188** [comment]
Да основные функции проверил, эффекты, яркость, вкл. выкл., но у меня прошивка не гайвера, а 89 эффектов с web интерфейсом.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/GyverLamp/releases/tag/v1.1.0
