### ISSUE TITLE
После обновления HA core-2024.3.0 появилось предупреждение.

### ISSUE THREAD

**Issue by seny110188** [AlexxIT/GyverLamp#14]
Logger: homeassistant.components.light
Source: components/light/__init__.py:914
Integration: Освещение (documentation, issues)
First occurred: 21:05:42 (1 occurrences)
Last logged: 21:05:42

light.gyver_lamp (<class 'custom_components.gyverlamp.light.GyverLamp'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/AlexxIT/GyverLamp/issues

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/GyverLamp/releases/tag/v1.1.1
