### ISSUE TITLE
После обновления на HA 2024.8.2 появились предупреждения

### ISSUE THREAD

**Issue by f1x6r** [AlexxIT/GyverLamp#15]
Регистратор: homeassistant.helpers.frame
Источник: helpers/frame.py:151
Первое сообщение: 18:23:28 (1 сообщений)
Последнее сообщение: 18:23:28

Detected code that calls async_forward_entry_setup for integration gyverlamp with title: 192.168.3.15 and entry_id: 01J4ZHBKE63CVNHVJ70Y37MWHX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

и так же:

Регистратор: homeassistant.helpers.frame
Источник: helpers/frame.py:184
Первое сообщение: 18:23:28 (5 сообщений)
Последнее сообщение: 18:23:40

Detected that custom integration 'gyverlamp' calls async_forward_entry_setup for integration, gyverlamp with title: 192.168.3.15 and entry_id: 01J4ZHBKE63CVNHVJ70Y37MWHX, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/gyverlamp/__init__.py, line 23: hass.async_create_task(coro), please create a bug report at https://github.com/AlexxIT/GyverLamp/issues

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/GyverLamp/releases/tag/v1.1.2
