### ISSUE TITLE
Перестанет работать в Home Assistant 2025.1

### ISSUE THREAD

**Issue by seny110188** [AlexxIT/GyverLamp#16]
Регистратор: homeassistant.helpers.frame
Источник: helpers/frame.py:156
Первое сообщение: 09:34:57 (2 сообщений)
Последнее сообщение: 09:34:57

Detected code that calls async_forward_entry_setup for integration gyverlamp with title: 192.168.1.57 and entry_id: 7bdec751059ec6c5979c171ae8804d3e, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by AlexxIT** [comment]
#15
