### ISSUE TITLE
HA Core 2025.1 upcoming async_forward_entry_setup removing

### ISSUE THREAD

**Issue by SergeyPomelov** [AlexxIT/GyverLamp#17]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 19:52:39 (2 occurrences)
Last logged: 19:52:40

Detected that custom integration 'gyverlamp' calls async_forward_entry_setup for integration, gyverlamp with title: 192.168.1.57 and entry_id: e74487ab9df37236c8c3ef24faf87a0c, which is deprecated, await async_forward_entry_setups instead at custom_components/gyverlamp/__init__.py, line 24: hass.async_create_task(coro). This will stop working in Home Assistant 2025.6, please report it to the author of the 'gyverlamp' custom integration
Detected that custom integration 'adaptive_lighting' calls async_forward_entry_setup for integration, adaptive_lighting with title: Main and entry_id: 077339cad16a83788673c8b866dae5a1, which is deprecated, await async_forward_entry_setups instead at custom_components/adaptive_lighting/__init__.py, line 69: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues

**Comment by AlexxIT** [comment]
#15 #16
