### ISSUE TITLE
HA Core 2025.1 upcoming magic-numbers removing

### ISSUE THREAD

**Issue by SergeyPomelov** [AlexxIT/GyverLamp#18]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1329
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 19:52:39 (2 occurrences)
Last logged: 19:52:40

Entity None (<class 'custom_components.gyverlamp.light.GyverLamp'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|17: 21> and color modes, please report it to the author of the 'gyverlamp' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by AlexxIT** [comment]
This was fixed long time ago.
