### ISSUE TITLE
HA Core 2025.1 demands supported color modes list

### ISSUE THREAD

**Issue by SergeyPomelov** [AlexxIT/GyverLamp#19]
Logger: homeassistant.components.light
Source: components/light/__init__.py:1276
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 19:52:39 (2 occurrences)
Last logged: 19:52:40

None (<class 'custom_components.gyverlamp.light.GyverLamp'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'gyverlamp' custom integration

**Comment by AlexxIT** [comment]
Latest version supports color modes.
