### ISSUE TITLE
Сервис управления лампой Was: Поддержка нескольких ламп 

### ISSUE THREAD

**Issue by andrewjswan** [AlexxIT/GyverLamp#4]
Возможно ли добавить поддержку нескольких ламп?

**Comment by AlexxIT** [comment]
А разве не работает? Вообще базовая прошивка Гайвера весьма простенькая. Можете попробовать альтернативную
https://t.me/AlexxIT_SmartHome/368

**Comment by andrewjswan** [comment]
Вроде нет, прошивка у меня 83в1 :)
Хотелось бы ещё добавить сюда отсылку комманд на лампу типа добавить сервис
send_command
  command: P_ON и т.п.
  host: 192...

пн, 30 нояб. 2020 г., 16:51 Alex X <notifications@github.com>:

**Comment by AlexxIT** [comment]
Так несколько ламп нужно просто перечислить в конфиге. А включить лампу можно через сервис ХА. Вам нужно больше почитать про то, как работает ХА

**Comment by andrewjswan** [comment]
Включить не проблема, но допустим выставить будильник, с ХА уже не выйдет,
или вывести текст ну и другие служебные команды которые нельзя дёрнуть с
интерфейса ХА.
Я пробовал прописать две, в ХА вторая не появляется.

пн, 30 нояб. 2020 г., 22:04 Alex X <notifications@github.com>:

**Comment by AlexxIT** [comment]
Как вы прописывали две лампы?

**Comment by andrewjswan** [comment]
По простому:
light gyverlamp:
- platform: gyverlamp
  host: 192.168.1.123
- platform: gyverlamp
  host: 192.168.1.124

**Comment by sashayohan** [comment]
у меня конфиг такой же

```
light gyverlamp:
- platform: gyverlamp
  host: 192.168.1.74
- platform: gyverlamp
  host: 192.168.1.78
- platform: gyverlamp
  host: 192.168.1.108
```

Появляются light.gyver_lamp, light.gyver_lamp_2, light.gyver_lamp_3 и у всех название Gyver Lamp
Можно сделать возможность добавить имя? что то типа этого?

```
- platform: gyverlamp
  name: Nazvanie Lampi
  host: 192.168.1.108
```

Ну и ещё жалко конечно что не появляются в списке устройств, нельзя присвоить название комнаты в НА

**Comment by andrewjswan** [comment]
@sashayohan Спасибо, попробовал еще раз, да появилось.

@AlexxIT извините, был не прав.

Но насчет имени это было бы удобно, проще ими потом рулить.

И если возможно сервис отправки сообщений на лампы, можно будет тогда выставлять будильники, списки эффектов, таймер, отсылать сообщения и т.п.

**Comment by andrewjswan** [comment]
@AlexxIT а возможно добавить сервис который просто зашлет необходимую команду в лампу, не через службу light.turn_on с параметром effect: MSG-любойтекст, потому как в этом случае лампа включается если была выключена, а хотелось бы чтобы при отправке сообщения лампе она оставалась в том состоянии что была (кроме случаев с командами типа P_ON, P_OFF)?
Примерно как это сделано в Yeelight: YEELIGHT.SET_MODE
Тут сделать нечто типа: **gyver.send_message** c параметром entity_id: и data: тогда можно будет ее вызвать и лампа будет в том состоянии в котором она сейчас есть (включена, выключена).
