### ISSUE TITLE
Лампа перестает управляться из НА

### ISSUE THREAD

**Issue by andrewjswan** [AlexxIT/GyverLamp#5]
Добрый день!

Примерно через сутки-двое, лампа перестает откликатся на управление их НА, в логах начинает сыпать предупреждениями:
````2020-12-29 11:57:38 WARNING (MainThread) [homeassistant.components.light] Updating gyverlamp light took longer than the scheduled update interval 0:00:30
2020-12-29 11:58:08 WARNING (MainThread) [homeassistant.components.light] Updating gyverlamp light took longer than the scheduled update interval 0:00:30
2020-12-29 11:58:38 WARNING (MainThread) [homeassistant.components.light] Updating gyverlamp light took longer than the scheduled update interval 0:00:30
2020-12-29 11:59:08 WARNING (MainThread) [homeassistant.components.light] Updating gyverlamp light took longer than the scheduled update interval 0:00:30
2020-12-29 11:59:38 WARNING (MainThread) [homeassistant.components.light] Updating gyverlamp light took longer than the scheduled update interval 0:00:30
````
Из Программы при этом управляется без проблем, перезапуск интеграции помогает, но опять примерно на сутки двое ... Это как то решаемо?

**Comment by andrewjswan** [comment]
Может как то можно анализировать статус лампы, и если он непонятный перезапускать интеграцию автоматом? А то приходится или приложением лампу тушить или интеграцию руками перезапускать и опять на пару часов все Ок!

**Comment by pavlikru** [comment]
Да, такая же ситуация

**Comment by glebsterx** [comment]
Было так же, смотрел в логи с работы, пришел домой дал команду на включение - все сработало.. но в чем именно проблема так и не понял. Хотя возможно я перезагружал ХА..

**Comment by AlexxIT** [comment]
В теории в последней версии нет проблем

**Comment by glebsterx** [comment]
Да, версия вчера была старая, из моего репозитория, сегодня обновился но еще не проверял.. 
А еще в ридми было бы хорошо указать, что при оформлении списка эффектов названия эффектов состоящие более чем одного слова - нужно брать в кавычки =)

**Comment by AlexxIT** [comment]
Странно про кавычки. При каких настройка НЕ работает?

**Comment by glebsterx** [comment]
Настройки:
```
light gyverlamp:
- platform: GyverLamp
  host: 192.168.0.22
  effects:
    - Конфетти
    - Огонь
    - Водопад
```
ошибка: 
`Invalid config for [light.GyverLamp]: [effects] is an invalid option for [light.GyverLamp]. Check: light.GyverLamp->effects. (See ?, line ?).`
ну и по теме разумеется
`Updating GyverLamp light took longer than the scheduled update interval 0:00:30`
но это я думаю сама лампа зависает.. хотяя..

**Comment by AlexxIT** [comment]
@glebsterx точно это всё на последней версии?

**Comment by glebsterx** [comment]
@AlexxIT я кажется разобрался - при обновлении через HACS - создается папка в нижнем регистре, а у меня была почему-то "GyverLamp".. соответственно было 2 папки и ХА читал старый компонент.. короче сам виноват.

**Comment by andrewjswan** [comment]
> В теории в последней версии нет проблем

HACS говорит обновлений нет, но проблема есть ... :( возникает примерно через часов 12 после старта, ну или через часа 3 после перезагрузки интеграции ...

**Comment by AlexxIT** [comment]
HACS иногда врёт, в файле manifest должна быть версия 1.0.1

**Comment by andrewjswan** [comment]
Да, похоже врёт, тк версии нет, обновлю, проверю... Спасибо.
